swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /{email}:
    parameters:
      - name: email
        in: path
        type: string
    get:
      parameters:
        - name: email
          in: query
          type: string
      responses:
        200:
          description: OK