openapi: 3.0.0

paths:
  /feature-a:
    get:
      summary: Feature A
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items: { type: string }